// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {websocket} from '../models';

export function CopyToClipboard(arg1:string):Promise<string>;

export function ListenContent(arg1:websocket.Conn):Promise<void>;

export function StartServer():Promise<void>;
