// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ListenContent(arg1) {
  return window['go']['main']['App']['ListenContent'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}
